[package]
name = "ssh-vc-pam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"pam-bindings" = { git = "https://github.com/anowell/pam-rs.git" }

[lib]
crate-type = ["cdylib"]
